packages:
  - "apps/*"
  - "automation/*"
  - "packages/*"
  - "tools/*"

catalog:
  "@biomejs/biome": ^2.4.12
  "@types/node": ^24.7.2
  "@playwright/test": ^1.54.2
  pyright: ^1.1.409
  typescript: ^5.9.3
