import {
  buildClientPortalStabilityContract,
  type ClientPortalWorkspaceRecord,
  ClientPortalWorkspaceRepository,
} from "../../../packages/backend-northbound/src/index.ts";
import { buildClientPortalWorkspace } from "../../../packages/backend-portal/src/index.ts";
import type {
  CrossDeviceContinuityContract,
  SemanticAccessibilityContract,
  ShellDominanceContract,
  ShellStateTaxonomyContract,
} from "../../../packages/generated-models/src/generated/typescript/surface-and-experience.ts";
import { actorContext } from "./post_commands_fixtures.ts";

export const portalReadTenantId = "tenant.taxat-sandbox";
export const portalReadClientId = "client.taxpayer-2001";
export const portalReadActorContext = actorContext({
  client_id_or_null: portalReadClientId,
  principal_ref: "principal.client-2001",
  session_ref: "session.portal-client-1",
  tenant_id: portalReadTenantId,
});

const accessBindingHash = "access.portal.client-2001";
const maskingFingerprint = "mask.portal.full";
const visibilityCachePartitionKey = "visibility.portal.client-2001";
const workspaceVersion = 12;
const viewGuardRef = "view-guard.portal.12";

function languageContract() {
  return {
    contract_code: "PORTAL_LANGUAGE_CONTRACT_V1",
    copy_budget: {
      action_label_max_chars: 36,
      approval_change_digest_max_chars: 180,
      approval_receipt_next_step_max_chars: 96,
      approval_summary_max_chars: 180,
      approval_title_max_chars: 72,
      dominant_question_max_chars: 120,
      help_first_view_char_budget: 420,
      help_headline_max_chars: 96,
      help_option_label_max_chars: 40,
      home_first_view_char_budget: 520,
      onboarding_first_view_char_budget: 480,
      onboarding_step_label_max_chars: 64,
      reassurance_line_max_chars: 120,
      request_detail_first_view_char_budget: 460,
      request_due_label_max_chars: 64,
      request_help_text_max_chars: 180,
      request_row_action_label_max_chars: 36,
      request_row_due_label_max_chars: 64,
      request_row_no_safe_action_max_chars: 120,
      request_row_status_label_max_chars: 48,
      request_row_title_max_chars: 72,
      request_title_max_chars: 72,
      request_why_label_max_chars: 120,
      status_due_label_max_chars: 48,
      status_headline_max_chars: 96,
      status_supporting_text_max_chars: 180,
      task_description_max_chars: 180,
      task_label_max_chars: 72,
      timeline_detail_max_chars: 180,
      timeline_headline_max_chars: 120,
    },
    copy_serialization_policy: "DIRECT_TEXT_OR_GOVERNED_TEXT_REF_ONLY",
    dominance_policy: "ONE_DOMINANT_QUESTION_AND_ONE_PRIMARY_ACTION",
    due_label_policy: "EXPLICIT_DUE_DATE_OR_NO_DEADLINE",
    forbidden_term_families: [
      "GATE_LANGUAGE",
      "MANIFEST_LANGUAGE",
      "STALE_OR_REBASE_JARGON",
      "OVERRIDE_LANGUAGE",
      "AUDIT_LANGUAGE",
      "ESCALATION_LANGUAGE",
      "ASSIGNMENT_LANGUAGE",
      "STAFF_ROLE_LANGUAGE",
      "WORKFLOW_LANGUAGE",
      "INTERNAL_ONLY_LANGUAGE",
    ],
    history_language_policy: "CURRENT_PRIMARY_HISTORY_EXPLICIT",
    plain_language_policy: "CLIENT_SAFE_LITERAL_TASK_LANGUAGE",
    role_filter_policy: "ROLE_FILTER_BEFORE_COPY_PUBLICATION",
    settlement_language_policy: "PENDING_AND_SETTLED_EXPLICIT",
    support_subordination_policy: "ONE_PROMOTED_SUPPORT_REGION_SUBORDINATE_TO_TASK",
  };
}

function portalInteractionLayer() {
  return {
    artifact_hierarchy_policy: "CURRENT_PRIMARY_HISTORY_SECONDARY",
    feedback_truth_policy: "DURABLE_RECEIPT_AND_TYPED_FAILURE_DRIVEN",
    focus_restoration_policy: "RETURN_FOCUS_ANCHOR_THEN_LATEST_VISIBLE",
    foundation_contract: {
      continuity_policy: "SAME_SHELL_CONTEXTUAL_RETURN",
      contract_version: "INTERACTION_LAYER_FOUNDATION_V1",
      design_token_binding_policy: "SERVER_PUBLISHED_TOKENS_ONLY",
      feedback_truth_policy: "DURABLE_RECEIPT_AND_TYPED_FAILURE_DRIVEN",
      history_presentation_policy: "CURRENT_PRIMARY_HISTORY_SECONDARY",
      layout_density_token: "PORTAL_COMFORTABLE_TASK_DENSITY_V1",
      motion_profile: "SUBTLE_CAUSAL_ONLY",
      motion_token: "MOTION_140_180MS_NO_BOUNCE",
      notification_surface_policy: "CONTEXT_BOUND_INLINE_FEEDBACK",
      platform_parity_policy: "WEB_NATIVE_SEMANTIC_PARITY",
      preview_surface_policy: "PRIMARY_CONTEXT_WITH_STACKED_SUPPORT",
      recovery_surface_policy: "INLINE_REVIEW_OR_RECOVERY_NOTICE",
      responsive_compaction_token: "PORTAL_STACK_BELOW_PRIMARY_V1",
      secondary_window_policy: "NOT_APPLICABLE",
      selector_profile: "PORTAL_SEMANTIC_SELECTORS_V1",
      shell_family: "CLIENT_PORTAL_SHELL",
      support_surface_policy: "ONE_PROMOTED_SUPPORT_SURFACE_MAX",
      support_surface_spacing_token: "PORTAL_INLINE_SUPPORT_SPACING_V1",
      surface_spacing_token: "PORTAL_PRIMARY_STACK_SPACING_V1",
    },
    motion_profile: "SUBTLE_CAUSAL_ONLY",
    navigation_model: "TOP_LEVEL_TABS_CONTEXTUAL_DETAIL",
    responsive_detail_policy: "STACK_SUPPORT_BELOW_PRIMARY",
    route_continuity_policy: "SAME_SHELL_CONTEXTUAL_RETURN",
    selector_profile: "PORTAL_SEMANTIC_SELECTORS_V1",
    spacing_profile: "COMFORTABLE_TASK_FIRST",
    status_language_profile: "PLAIN_LITERAL_CLIENT_SAFE",
    support_region_policy: "ONE_PROMOTED_REGION_MAX",
  };
}

function visibilityPartition() {
  return {
    access_binding_hash: accessBindingHash,
    allowed_visibility_classes: ["CUSTOMER_VISIBLE"],
    audience_class: "CLIENT_PORTAL",
    badge_counter_policy: "SURFACE_VISIBLE_ONLY",
    cache_partition_key: visibilityCachePartitionKey,
    export_scope_policy: "MOUNTED_ROUTE_VISIBILITY_ONLY",
    fallback_discovery_policy: "NO_CROSS_PARTITION_DISCOVERY",
    limited_state_presentation: "EXPLICIT_LIMITATION_NOTICE",
    masking_posture_fingerprint: maskingFingerprint,
    ordering_side_channel_policy: "VISIBLE_EVENTS_ONLY",
    partition_scope: "CLIENT_PORTAL_WORKSPACE",
  };
}

function customerSafeProjection(boundaryScope = "CLIENT_PORTAL_WORKSPACE") {
  return {
    access_binding_hash: accessBindingHash,
    artifact_history_policy: "CURRENT_VERSUS_HISTORY_EXPLICIT",
    attachment_visibility_policy: "CUSTOMER_VISIBLE_ATTACHMENTS_ONLY",
    blocked_staff_signal_classes: [
      "ASSIGNMENT_STATE",
      "ESCALATION_LOGIC",
      "RAW_GATE_STATE",
      "STAFF_REASON_CODES",
      "AUDIT_LINEAGE",
      "INTERNAL_ACTIVITY",
      "INTERNAL_ATTACHMENTS",
      "INTERNAL_PARTICIPANTS",
      "INTERNAL_COUNTS",
      "STAFF_ROUTE_CONTEXT",
    ],
    boundary_scope: boundaryScope,
    contract_version: "CUSTOMER_SAFE_PROJECTION_V1",
    draft_placeholder_policy: "CUSTOMER_SAFE_PROJECTIONS_EXCLUDE_INTERNAL_DRAFTS",
    export_visibility_policy: "CUSTOMER_VISIBLE_EXPORTS_ONLY",
    hidden_activity_policy: "NO_HIDDEN_ACTIVITY_DERIVATION",
    limitation_notice_policy: "EXPLICIT_CUSTOMER_SAFE_NOTICE_REQUIRED",
    live_update_visibility_policy: "INTERNAL_ONLY_DELTA_EXCLUSION_REQUIRED",
    masking_posture_fingerprint: maskingFingerprint,
    module_projection_policy: "CUSTOMER_SAFE_MODULES_AND_METADATA_ONLY",
    notification_navigation_policy: "PORTAL_SAME_SHELL_AND_VISIBILITY_ONLY",
    plain_language_action_policy: "CUSTOMER_SAFE_ACTION_VOCABULARY_ONLY",
    plain_language_status_policy: "CUSTOMER_SAFE_STATUS_VOCABULARY_ONLY",
    projection_audience: "CLIENT_PORTAL",
    recovery_explanation_policy: "EXPLICIT_CUSTOMER_SAFE_RECOVERY_NOTICE_REQUIRED",
    shell_family: "CLIENT_PORTAL_SHELL",
    staff_field_dependency_policy: "EXCLUDE_STAFF_FIELDS_AT_PROJECTION_SOURCE",
    status_derivation_policy: "CUSTOMER_SAFE_BLOCKS_ONLY",
    visibility_cache_partition_key: visibilityCachePartitionKey,
  };
}

function dominanceContract() {
  return {
    contract_version: "SHELL_DOMINANCE_V1",
    detached_support_policy: "SUPPORT_ONLY_NEVER_PRIMARY",
    dominant_action_ref_or_null: "task.document.id",
    dominant_action_surface_code: "STATUS_HERO",
    dominant_question_surface_code: "STATUS_HERO",
    explicit_multifocus_mode: "DEFAULT",
    parallel_primary_posture: "DISALLOWED",
    promoted_support_surface_code_or_null: null,
    renderer_salience_policy: "SERVER_AUTHORED_ONLY",
    responsive_collapse_policy: "PRESERVE_DOMINANT_SUMMARY_AND_ACTION",
    safe_action_state: "ACTION_AVAILABLE",
    summary_action_alignment_policy: "SAME_DOMINANT_QUESTION",
    supplemental_queue_policy: "SECONDARY_TO_PRIMARY_ACTION",
    support_surface_role: "SUBORDINATE",
  } satisfies ShellDominanceContract;
}

function stateTaxonomyContract() {
  return {
    contract_version: "SHELL_STATE_TAXONOMY_V1",
    current_empty_state_or_null: null,
    current_empty_surface_code_or_null: null,
    current_recovery_posture: "NONE",
    current_settlement_state: "STEADY",
    generic_placeholder_policy: "FORBID_GENERIC_EMPTY_SPINNER_WARNING",
    limitation_reason_codes: [],
    limitation_reason_policy: "LIMITED_REQUIRES_EXPLICIT_REASON_CODES",
    loading_strategy: "INLINE_PRESERVE_PRIOR_CONTENT",
    mounted_context_state: "PRESERVED",
    profile_copy_policy: "PROFILE_COPY_MUST_MAP_TO_SHARED_TAXONOMY",
    recovery_navigation_policy: "PRESERVE_CURRENT_OBJECT_UNLESS_SUPERSEDED",
    stale_action_policy: "STALE_DEGRADED_AND_RECOVERY_REQUIRE_NO_SAFE_ACTION",
  } satisfies ShellStateTaxonomyContract;
}

function crossDeviceContinuityContract() {
  return {
    access_scope_hash_or_null: accessBindingHash,
    action_posture_policy: "DOMINANCE_AND_SETTLEMENT_SERVER_AUTHORED_ONLY",
    allowed_embodiments: ["BROWSER_WIDE", "BROWSER_NARROW_STACKED"],
    canonical_object_ref: "portal.workspace.client-2001",
    compatibility_basis_class: "ROUTE_GUARD_AND_VISIBILITY",
    continuity_scope: "CLIENT_PORTAL_ROUTE",
    contract_version: "CROSS_DEVICE_CONTINUITY_V1",
    deep_link_return_policy: "EXPLICIT_PARENT_CONTEXT_AND_FOCUS",
    dominant_action_state_or_null: "ACTION_AVAILABLE",
    focus_anchor_ref_or_null: null,
    hydration_compatibility_policy: "TENANT_ACCESS_MASKING_AND_SESSION_BOUND",
    masking_scope_fingerprint_or_null: maskingFingerprint,
    narrow_layout_policy: "STACK_WITHIN_SAME_SHELL",
    parent_context_ref_or_null: null,
    restoration_mode_policy: "EXPLICIT_CARRY_FORWARD_OR_REBASE_ONLY",
    return_focus_anchor_ref_or_null: null,
    route_identity_ref: "HOME",
    same_object_policy: "PRESERVE_EXACT_OBJECT_OR_EXPLICIT_LAWFUL_FALLBACK",
    same_shell_policy: "PRESERVE_SAME_SHELL_FAMILY",
    secondary_window_policy: "NOT_APPLICABLE",
    session_scope_ref_or_null: "session.portal-client-1",
    shell_family: "CLIENT_PORTAL_SHELL",
    stability_guard_hash_or_null: "pending-until-route-projection",
    supported_invalidation_reason_codes: [
      "ROUTE_GUARD_CHANGED",
      "VISIBILITY_CHANGED",
      "SESSION_REVOKED",
    ],
    visibility_cache_partition_key_or_null: visibilityCachePartitionKey,
  } satisfies CrossDeviceContinuityContract;
}

function semanticAccessibilityContract() {
  return {
    announced_change_kinds: [
      "ACTIVITY_DELTA",
      "BADGE_DELTA",
      "RECOVERY_NOTICE",
      "COMMAND_FAILURE",
      "TERMINAL_SETTLEMENT",
    ],
    artifact_handoff_policy: "CURRENT_AND_HISTORY_ANCHORS_SEPARATE",
    browser_identifier_policy: "DATA_TESTID_MIRRORS_SEMANTIC_ANCHOR",
    conditional_notice_anchor_policy: "LIMITATION_AND_RECOVERY_NOTICES_REQUIRE_ADDRESSABLE_ANCHORS",
    contract_version: "SEMANTIC_ACCESSIBILITY_V1",
    detail_module_access_policy: "SUPPORT_MODULES_KEYBOARD_AND_ASSISTIVE_TECH_REACHABLE",
    focus_entry_policy: "REQUESTED_ANCHOR_OR_PRIMARY_HEADING_OR_EXPLICIT_NOTICE",
    focus_order_policy: "VISIBLE_SEMANTIC_ORDER_ONLY",
    focus_restore_policy: "RETURN_TO_INVOKER_OR_LAWFUL_ANCESTOR",
    heading_navigation_policy: "PRIMARY_HEADING_AND_PROMOTED_REGION_HEADINGS",
    identifier_semantics_policy: "DOMAIN_MEANING_OVER_VISUAL_STYLING",
    keyboard_completion_policy: "ALL_GOVERNED_ACTIONS_KEYBOARD_OPERABLE",
    landmark_structure_policy: "STABLE_SHELL_SUMMARY_ACTION_SUPPORT_AND_NOTICE_LANDMARKS",
    live_region_policy: "POLITE_ACTIVITY_ASSERTIVE_FAILURE_ONLY",
    live_update_focus_policy: "NEVER_STEAL_ACTIVE_INPUT_OR_PICKER_FOCUS",
    native_identifier_policy: "ACCESSIBILITY_IDENTIFIER_MIRRORS_SEMANTIC_ANCHOR",
    reduced_motion_policy: "MEANING_PRESERVED_WITH_MINIMAL_OR_NO_MOTION",
    required_anchor_codes: [
      "SHELL_ROOT",
      "SHELL_FAMILY",
      "OBJECT_ANCHOR",
      "DOMINANT_QUESTION",
      "DOMINANT_ACTION",
      "SETTLEMENT_POSTURE",
      "RECOVERY_POSTURE",
      "SECTION_NAV",
      "WORKSPACE_HEADER",
      "STATUS_HERO",
      "TASK_QUEUE",
      "DOCUMENT_CENTER",
      "APPROVAL_CENTER",
      "SUPPORT_PANEL",
      "RECOVERY_NOTICE",
    ],
    selector_profile: "PORTAL_SEMANTIC_SELECTORS_V1",
    semantic_focus_order: [
      "WORKSPACE_HEADER",
      "SECTION_NAV",
      "DOMINANT_ACTION",
      "PROMOTED_SUPPORT_REGION",
    ],
    shell_family: "CLIENT_PORTAL_SHELL",
    support_region_access_policy: "PROMOTED_SUPPORT_REGION_KEYBOARD_REACHABLE_AND_ESCAPABLE",
  } satisfies SemanticAccessibilityContract;
}

function uploadBindingContract() {
  return {
    attachment_authority_policy: "ATTACH_ONLY_TO_CURRENT_OR_RECONFIRMED_REQUEST",
    binding_resolution_basis: "ORIGINAL_FROZEN_REQUEST",
    contract_version: "UPLOAD_REQUEST_BINDING_V1",
    cross_device_resume_policy: "CROSS_DEVICE_RESUME_REUSES_EXISTING_SESSION",
    duplicate_file_policy: "REUSE_FROZEN_STORAGE_REF_ON_RESUME_OR_RETRY",
    duplicate_session_policy: "NO_DUPLICATE_SESSION_ON_RECONNECT",
    frozen_binding_scope_hash:
      "tenant.taxat-sandbox|client.taxpayer-2001|request.identity|request.identity.v2",
    frozen_client_id: portalReadClientId,
    frozen_request_id: "request.identity",
    frozen_request_version_ref: "request.identity.v2",
    frozen_tenant_id: portalReadTenantId,
    inflight_rebase_policy: "IN_FLIGHT_REBASE_PRESERVES_SESSION_UNTIL_TRANSFER_TERMINATES",
    live_request_version_ref: "request.identity.v2",
    next_action_authority_policy: "TRANSFER_AND_BINDING_STATE_DETERMINE_NEXT_ACTION",
    rebase_detected_at_or_null: null,
    request_binding_state: "ORIGINAL_CURRENT",
    request_identity_ref: "request.identity",
    resume_identity_policy: "RESUME_EXISTING_SESSION_ONLY",
    stale_completion_policy: "STALE_BYTES_NEVER_SATISFY_CURRENT_REQUEST",
  };
}

function externalizationContract(boundaryScope: string, contextAnchorRef: string) {
  return {
    access_binding_hash_or_null: accessBindingHash,
    approval_requirement_token_or_null: null,
    approval_state: "NOT_REQUIRED",
    background_scope_policy: "DETACHED_BACKGROUND_SCOPE_FORBIDDEN",
    blocking_context_tokens: [],
    boundary_scope: boundaryScope,
    context_anchor_ref: contextAnchorRef,
    contract_version: "EXTERNALIZATION_GOVERNANCE_V1",
    delivery_binding_hash: `delivery.${boundaryScope}.${contextAnchorRef}`,
    delivery_context_policy: "TENANT_AND_SECURITY_CONTEXT_BOUND_AT_INVOCATION",
    delivery_surface_kind: "CLIENT_PORTAL_ARTIFACT",
    direct_url_policy: "DIRECT_URL_BYPASS_FORBIDDEN",
    eligibility_state: "READY",
    external_handoff_target_ref_or_null: null,
    handoff_target_policy: "EXTERNAL_TARGET_AND_BLOCKING_CONTEXT_EXPLICIT",
    history_meaning_state: "CURRENT_WITH_HISTORY_EXPLICIT",
    limitation_state: "FULL",
    masking_posture_fingerprint_or_null: maskingFingerprint,
    masking_state: "NONE",
    posture_preservation_policy: "CURRENT_HISTORY_MASKING_LIMITATION_AND_APPROVAL_PRESERVED",
    preview_target_ref_or_null: `${contextAnchorRef}.preview`,
    print_target_ref_or_null: `${contextAnchorRef}.print`,
    reentry_validation_policy: "RETURN_AND_DELIVERY_REQUIRE_GOVERNED_REVALIDATION",
    shell_family_or_null: "CLIENT_PORTAL_SHELL",
    signed_url_binding_policy: "SIGNED_URLS_REQUIRE_CURRENT_GOVERNED_BINDING",
    slice_binding_policy: "ACTIVE_GOVERNED_SLICE_REQUIRED",
    slice_binding_ref: `${contextAnchorRef}.slice`,
    temporary_artifact_policy: "TEMP_FILES_AND_NATIVE_PREVIEWS_REQUIRE_MATCHING_BINDING",
    tenant_id: portalReadTenantId,
    visibility_cache_partition_key_or_null: visibilityCachePartitionKey,
    download_target_ref_or_null: `${contextAnchorRef}.download`,
  };
}

function artifactSelection(scope: string, subjectRef: string) {
  return {
    authoritative_subject_refs: [subjectRef],
    default_download_target_ref_or_null: subjectRef,
    default_preview_target_ref_or_null: subjectRef,
    default_print_target_ref_or_null: subjectRef,
    historical_subject_refs: [],
    limited_history_count_or_null: null,
    limited_history_state: "NONE",
    presentation_mode: "CURRENT_PRIMARY_HISTORY_SECONDARY",
    primary_subject_refs: [subjectRef],
    selection_scope: scope,
  };
}

function artifactAffordance(scope: string, subjectRef: string) {
  return {
    affordance_scope: scope,
    contract_version: "ARTIFACT_AFFORDANCE_V1",
    default_download_target_ref_or_null: subjectRef,
    default_preview_target_ref_or_null: subjectRef,
    default_print_target_ref_or_null: subjectRef,
    header_posture: "CURRENT_PRIMARY",
    history_affordance_state: "CURRENT_ONLY",
    invocation_validation_policy: "VISIBLE_PRIMARY_AND_DEFAULT_TARGETS_MUST_MATCH_GOVERNED_POSTURE",
    label_visibility_policy: "EXPLICIT_POSTURE_LABELS_REQUIRED",
    preview_open_policy: "SAME_SHELL_PREVIEW_FIRST",
    primary_slot_policy: "CURRENT_PRIMARY_HISTORY_EXPLICIT",
    primary_subject_role: "CURRENT_ARTIFACT",
    visible_primary_subject_ref_or_null: subjectRef,
  };
}

export function clientPortalWorkspaceFixture(): ClientPortalWorkspaceRecord {
  const projectedWorkspace: ClientPortalWorkspaceRecord | null =
    buildClientPortalWorkspace() as ClientPortalWorkspaceRecord;
  if (projectedWorkspace !== null) {
    return projectedWorkspace;
  }
  const stabilityContract = buildClientPortalStabilityContract({
    publicationGeneration: 3,
    viewGuardRef,
    workspaceVersion,
  });
  return {
    activity_timeline: [
      {
        detail: "We received the identity document and will review it next.",
        event_id: "activity.upload.received",
        event_kind: "UPLOAD_RECEIVED",
        headline: "Document received",
        occurred_at: "2026-05-03T09:40:00.000Z",
      },
      {
        detail: "Your declaration is ready to review.",
        event_id: "activity.approval.ready",
        event_kind: "APPROVAL_READY",
        headline: "Approval ready",
        occurred_at: "2026-05-03T09:10:00.000Z",
      },
    ],
    approval_center: {
      latest_pack_ref: "approval.pack.2026",
      outstanding_count: 1,
      packs: [
        {
          approval_acknowledged: true,
          approval_pack_id: "approval.pack.2026",
          approval_readiness_score: 91,
          artifact_affordance: artifactAffordance("CLIENT_APPROVAL_PACK", "approval.pack.2026"),
          artifact_selection: artifactSelection("CLIENT_APPROVAL_PACK", "approval.pack.2026"),
          change_digest_acknowledged: true,
          change_digest_summary: "One declaration is ready for your review.",
          change_highlight_count: 1,
          change_highlights_ref: "copy.approval.change-highlights",
          declaration_acknowledged: true,
          declaration_download_ref: "artifact.approval.declaration.download",
          declaration_print_ref: "artifact.approval.declaration.print",
          declaration_text_ref: "copy.approval.declaration",
          dominant_hazard_code: null,
          due_at: "2026-05-10T12:00:00.000Z",
          externalization_governance_contract: externalizationContract(
            "CLIENT_APPROVAL_PACK",
            "approval.pack.2026",
          ),
          primary_action: {
            action_code: "SIGN_APPROVAL",
            context_object_ref: "approval.pack.2026",
            focus_anchor_ref: "approval.pack.2026.sign",
            label: "Sign now",
            requires_step_up: true,
            route: "APPROVALS",
          },
          receipt_download_ref: null,
          receipt_issued_at: null,
          receipt_next_step_label: null,
          receipt_print_ref: null,
          receipt_ref: null,
          receipt_state: "NOT_ISSUED",
          recovery_posture: "NONE",
          requires_step_up: true,
          settlement_pending_label: null,
          sign_command_receipt_ref: null,
          sign_off_state: "STEP_UP_CHECKPOINT",
          stale_protection_state: "CURRENT",
          status: "STEP_UP_REQUIRED",
          step_up_checkpoint_state: "REQUIRED",
          step_up_surface: "INLINE_CHECKPOINT",
          summary: "Please review and sign the declaration.",
          superseded_by_pack_ref: null,
          title: "Tax declaration approval",
        },
      ],
      surface_order: ["APPROVAL_SUMMARY", "CHANGE_DIGEST", "DECLARATION_PANEL", "SIGN_OFF_PANEL"],
    },
    artifact_type: "ClientPortalWorkspace",
    cache_isolation_contract: {
      access_binding_hash_or_null: accessBindingHash,
      cache_partition_ref: "cache.portal.client-2001",
      cache_scope_class: "CLIENT_PORTAL_WORKSPACE",
      canonical_object_ref: "portal.workspace.client-2001",
      client_id_or_null: portalReadClientId,
      customer_safe_projection: true,
      delivery_binding_hash: null,
      masking_posture_fingerprint_or_null: maskingFingerprint,
      preview_subject_ref_or_null: null,
      principal_class: "CLIENT_CONTRIBUTOR",
      projection_version_ref: String(workspaceVersion),
      route_identity_ref: "HOME",
      session_binding_hash: "session.portal-client-1",
      shell_family: "CLIENT_PORTAL_SHELL",
      shell_stability_ref_or_null: null,
      tenant_id: portalReadTenantId,
      visibility_cache_partition_key_or_null: visibilityCachePartitionKey,
    },
    client_id: portalReadClientId,
    content_limitations: [],
    cross_device_continuity_contract: {
      ...crossDeviceContinuityContract(),
      stability_guard_hash_or_null: stabilityContract.guard_vector_hash,
    },
    customer_safe_projection: customerSafeProjection(),
    document_center: {
      last_uploaded_at: "2026-05-03T09:40:00.000Z",
      open_request_count: 2,
      requests: [
        {
          accepted_file_types: ["application/pdf", "image/jpeg"],
          artifact_affordance: artifactAffordance(
            "CLIENT_DOCUMENT_REQUEST",
            "upload.identity.current",
          ),
          artifact_selection: artifactSelection(
            "CLIENT_DOCUMENT_REQUEST",
            "upload.identity.current",
          ),
          category: "IDENTITY",
          current_artifact_upload_ref: "upload.identity.current",
          current_upload_ref: "upload.identity.current",
          due_at: "2026-05-10T12:00:00.000Z",
          due_label: "Due 10 May 2026",
          externalization_governance_contract: externalizationContract(
            "CLIENT_DOCUMENT_REQUEST",
            "request.identity",
          ),
          help_text: "Please use a clear scan or photo.",
          max_file_size_mb: 25,
          request_id: "request.identity",
          request_version_ref: "request.identity.v2",
          status: "UNDER_REVIEW",
          title: "Photo ID",
          uploads: [
            {
              attachment_state: "CONFIRMATION_REQUIRED",
              dominant_hazard_code: null,
              download_ref: "artifact.upload.identity.current.download",
              filename: "passport.pdf",
              history_state: "CURRENT",
              next_action_code: "CONFIRM_ATTACHMENT",
              preview_posture: "SAME_SHELL_PREVIEW",
              preview_reason_code: null,
              recovery_posture: "NONE",
              request_binding_state: "ORIGINAL_CURRENT",
              request_version_ref: "request.identity.v2",
              resumability_state: "CLOSED",
              status_phase: "VALIDATION",
              transfer_state: "ACCEPTED",
              upload_confidence_score: 94,
              upload_request_binding_contract: uploadBindingContract(),
              upload_session_id: "upload.identity.current",
              uploaded_at: "2026-05-03T09:40:00.000Z",
            },
          ],
          why_requested_label: "We need to confirm your identity.",
        },
        {
          accepted_file_types: ["application/pdf"],
          artifact_affordance: artifactAffordance(
            "CLIENT_DOCUMENT_REQUEST",
            "request.bank-statement",
          ),
          artifact_selection: artifactSelection(
            "CLIENT_DOCUMENT_REQUEST",
            "request.bank-statement",
          ),
          category: "BANK_STATEMENT",
          current_artifact_upload_ref: null,
          current_upload_ref: null,
          due_at: "2026-05-12T12:00:00.000Z",
          due_label: "Due 12 May 2026",
          externalization_governance_contract: externalizationContract(
            "CLIENT_DOCUMENT_REQUEST",
            "request.bank-statement",
          ),
          help_text: "A recent statement is enough.",
          max_file_size_mb: 25,
          request_id: "request.bank-statement",
          request_version_ref: "request.bank-statement.v1",
          status: "OPEN",
          title: "Bank statement",
          uploads: [],
          why_requested_label: "We need proof of the account.",
        },
      ],
      status_phase_order: ["TRANSFER", "SCAN", "VALIDATION", "ACCEPTANCE", "REJECTION", "RETRY"],
      summary_label: "Two documents need attention",
      surface_order: ["DOCUMENT_INBOX", "UPLOAD_PANEL", "UPLOAD_STATUS_LIST", "DOCUMENT_HISTORY"],
      upload_affordances: ["BROWSE", "DRAG_DROP", "CAMERA_CAPTURE"],
    },
    dominance_contract: dominanceContract(),
    dominant_question: "What does the firm need from me next?",
    draft_resume: {
      draft_kind: "NONE",
      draft_object_ref: null,
      draft_state: "NONE",
      last_saved_at: "2026-05-03T09:00:00.000Z",
      rebase_target_ref: null,
      resume_route: null,
    },
    freshness_state: "FRESH",
    home_primary_task_ref: "task.upload.bank-statement",
    home_surface_order: ["PORTAL_HEADER", "STATUS_HERO", "TASK_QUEUE", "RECENT_ACTIVITY"],
    identity_context: {
      acting_role_label: "Contributor",
      client_display_name: "Taylor Example",
      context_hash: "identity-context.client-2001",
      delegated_session: true,
      period_label: "2025 to 2026",
      reassurance_line: "You are acting for Taylor Example for 2025 to 2026.",
    },
    interaction_layer: portalInteractionLayer(),
    language_contract: languageContract(),
    manifest_id: "manifest.portal.2026",
    navigation_tabs: [
      { active: true, badge_count: null, label: "Home", route: "HOME" },
      { active: false, badge_count: 2, label: "Documents", route: "DOCUMENTS" },
      { active: false, badge_count: 1, label: "Approvals", route: "APPROVALS" },
      { active: false, badge_count: 1, label: "Onboarding", route: "ONBOARDING" },
      { active: false, badge_count: null, label: "Help", route: "HELP" },
    ],
    object_anchor_ref: "portal.workspace.client-2001",
    onboarding_journey: {
      abandoned_at: null,
      abandonment_reason_code: null,
      completed_at: null,
      completed_step_count: 5,
      completion_next_steps_ref: null,
      completion_summary_ref: null,
      current_step_code: "REVIEW_CONFIRMATION",
      current_step_label: "Review and confirm",
      expired_at: null,
      journey_id: "onboarding.journey.2026",
      next_action: {
        action_code: "CONTINUE_ONBOARDING",
        context_object_ref: "onboarding.journey.2026",
        focus_anchor_ref: "onboarding.review",
        label: "Continue",
        route: "ONBOARDING",
      },
      reconfirmation_step_codes: [],
      resume_state: "LIVE",
      resume_step_code: "REVIEW_CONFIRMATION",
      save_and_return_action: {
        action_code: "SAVE_AND_RETURN",
        context_object_ref: "onboarding.journey.2026",
        focus_anchor_ref: "onboarding.review",
        label: "Save",
        route: "ONBOARDING",
      },
      save_return_state: "AVAILABLE",
      state: "READY_FOR_REVIEW",
      step_workspace_state: "ACTIVE_STEP",
      surface_order: ["WELCOME_PANEL", "ONBOARDING_STEPPER", "STEP_WORKSPACE", "SUPPORT_PANEL"],
      total_step_count: 6,
    },
    recovery_posture: "NONE",
    reliability_summary: {
      completion_probability: 0.83,
      dominant_abort_hazard_code: null,
      dominant_flow_kind: "GENERAL_NAVIGATION",
      flow_stability_score: 88,
      network_posture: "HEALTHY",
      recovery_posture: "NONE",
      risk_weighted_friction_score: 14,
      surface_class: "DESKTOP",
    },
    route: "HOME",
    route_context: {
      artifact_focus_bucket_or_null: null,
      artifact_focus_subject_ref_or_null: null,
      context_object_ref: null,
      context_route: "NONE",
      fallback_object_ref_or_null: null,
      fallback_reason_ref_or_null: null,
      fallback_target: null,
      focus_anchor_ref: null,
      focus_restoration: {
        requested_focus_anchor_ref_or_null: null,
        resolved_focus_anchor_ref_or_null: null,
        restoration_disposition: "EXACT_FOCUS",
        restoration_reason_code_or_null: null,
      },
      narrow_screen_mode: null,
      return_focus_anchor_ref_or_null: null,
      return_route: null,
    },
    semantic_accessibility_contract: semanticAccessibilityContract(),
    settlement_state: "STEADY",
    shell_family: "CLIENT_PORTAL_SHELL",
    stability_contract: stabilityContract,
    state_taxonomy_contract: stateTaxonomyContract(),
    status_hero: {
      due_label: "Due 12 May 2026",
      headline: "Upload your bank statement",
      primary_action: {
        action_code: "UPLOAD_DOCUMENT",
        context_object_ref: "request.bank-statement",
        focus_anchor_ref: "request.bank-statement.upload",
        label: "Upload now",
        route: "DOCUMENTS",
      },
      progress_steps: [
        { label: "Documents requested", state: "CURRENT", step_code: "DOCUMENTS" },
        { label: "Approval ready", state: "UPCOMING", step_code: "APPROVAL" },
      ],
      secondary_action: null,
      status_code: "ACTION_REQUIRED",
      supporting_text: "Please upload the statement so we can continue.",
    },
    support_panel: {
      case_context_panel: null,
      contact_options: [
        {
          action: {
            action_code: "REQUEST_HELP",
            label: "Ask for help",
            route: "HELP",
          },
          channel_code: "SECURE_MESSAGE",
          label: "Send a message",
        },
      ],
      faq_refs: ["faq.documents.accepted-files"],
      help_headline: "Need help with this filing?",
      secure_message_allowed: true,
      surface_order: null,
    },
    task_groups: [
      {
        group_code: "DO_NOW",
        label: "Do now",
        tasks: [
          {
            description: "Attach the recent statement so we can continue.",
            due_at: "2026-05-12T12:00:00.000Z",
            effort_label: "About 2 minutes",
            label: "Upload bank statement",
            primary_action: {
              action_code: "UPLOAD_DOCUMENT",
              context_object_ref: "request.bank-statement",
              focus_anchor_ref: "request.bank-statement.upload",
              label: "Upload now",
              route: "DOCUMENTS",
            },
            route: "DOCUMENTS",
            status: "OPEN",
            task_id: "task.upload.bank-statement",
            task_type: "UPLOAD_DOCUMENT",
          },
        ],
      },
      {
        group_code: "COMING_UP",
        label: "Coming up",
        tasks: [
          {
            description: "Your declaration is ready after document review.",
            effort_label: "About 3 minutes",
            label: "Review declaration",
            primary_action: {
              action_code: "REVIEW_APPROVAL",
              context_object_ref: "approval.pack.2026",
              focus_anchor_ref: "approval.pack.2026",
              label: "Review",
              route: "APPROVALS",
            },
            route: "APPROVALS",
            status: "WAITING",
            task_id: "task.review.approval",
            task_type: "SIGN_DECLARATION",
          },
        ],
      },
    ],
    tenant_id: portalReadTenantId,
    updated_at: "2026-05-03T10:00:00.000Z",
    view_guard_ref: viewGuardRef,
    viewer_role: "CLIENT_CONTRIBUTOR",
    visibility_partition: visibilityPartition(),
    workspace_id: "portal.workspace.client-2001",
    workspace_posture: {
      connection_state: "CONNECTED",
      full_text_ref: null,
      interaction_posture: "MUTATING_ALLOWED",
      notice_detail: null,
      notice_headline: null,
      promoted_support_region: "NONE",
    },
    workspace_version: workspaceVersion,
  };
}

export async function clientPortalReadRepositoriesFixture() {
  const clientPortalWorkspaceRepository = new ClientPortalWorkspaceRepository();
  const workspace = clientPortalWorkspaceFixture();
  await clientPortalWorkspaceRepository.persistWorkspace({
    sourceRefs: ["workflow.customer-safe.portal.fixture"],
    workspace,
  });
  return {
    clientPortalWorkspaceRepository,
    workspace,
  };
}
