import { expect, test } from "@playwright/test";

import {
  buildProvenanceEdgeRecord,
  buildProvenanceNodeRecord,
  deriveGraphAddress,
  deriveGraphId,
  deriveNodeGraphAddress,
  lineageBoundaryIdForEdge,
  type ProvenanceEdgeRecord,
  type ProvenanceNodeRecord,
  validateGraphIntegrity,
} from "../../../packages/backend-provenance/src/index.ts";

const createdAt = "2026-04-28T12:00:00Z";

function fixture() {
  const manifest_id = "manifest-0128-current";
  const prior_manifest_id = "manifest-0127-prior";
  const tenant_id = "tenant-0128";
  const client_id = "client-0128";
  const business_partition = "vat";
  const period_scope = "2026-Q1";
  const graph_id = deriveGraphId({
    business_partition,
    client_id,
    manifest_id,
    period_scope,
    tenant_id,
  });
  const graph_address = deriveGraphAddress({
    business_partition,
    client_id,
    graph_id,
    manifest_id,
    period_scope,
    tenant_id,
  });
  const node = (
    node_family: ProvenanceNodeRecord["node_family"],
    object_ref: string,
    manifest = manifest_id,
  ) =>
    buildProvenanceNodeRecord({
      business_partition,
      client_id,
      created_at: createdAt,
      graph_address: deriveNodeGraphAddress({
        business_partition,
        client_id,
        graph_id,
        manifest_id: manifest,
        node_family,
        object_ref,
        period_scope,
        tenant_id,
      }),
      graph_id,
      manifest_id: manifest,
      node_family,
      object_ref,
      period_scope,
      tenant_id,
    });
  const activity = node("AC_EVALUATE_GATE", "activity://evaluate-gate/0128");
  const gate = node("EN_GATE_DECISION", "gate-decision://0128");
  const evidence = node("EN_EVIDENCE_ITEM", "evidence-item://0128");
  const currentSource = node("EN_SOURCE_RECORD", "source-record://0128/current");
  const priorSource = node("EN_SOURCE_RECORD", "source-record://0128/prior", prior_manifest_id);
  const edge = (
    from: ProvenanceNodeRecord,
    to: ProvenanceNodeRecord,
    edge_type: ProvenanceEdgeRecord["edge_type"],
    extra: Partial<ProvenanceEdgeRecord> = {},
  ) =>
    buildProvenanceEdgeRecord({
      business_partition,
      client_id,
      created_at: createdAt,
      edge_type,
      from_node_id: from.node_id,
      graph_id,
      manifest_id,
      originating_activity_ref: activity.node_id,
      period_scope,
      tenant_id,
      to_node_id: to.node_id,
      ...extra,
    });
  return {
    edges: [
      edge(activity, gate, "ED_GENERATED"),
      edge(gate, evidence, "ED_SUPPORTS"),
      edge(evidence, currentSource, "ED_EXTRACTED_FROM"),
      edge(currentSource, priorSource, "ED_CONTINUES", {
        from_manifest_id: manifest_id,
        lineage_relation: "ED_CONTINUES",
        to_manifest_id: prior_manifest_id,
      }),
      edge(gate, evidence, "ED_CONTRADICTS", {
        admissibility_state: "LIMITED",
        contradicted_by_refs: [evidence.node_id],
        decisive_support: false,
        limitation_codes: ["EXPLICIT_CONTRADICTION"],
      }),
    ],
    graph_address,
    graph_id,
    manifest_id,
    nodes: [activity, gate, evidence, currentSource, priorSource],
    partition_contract: {
      client_id,
      contract_version: "PROVENANCE_PARTITION_V1" as const,
      cross_manifest_traversal_policy: "EXPLICIT_BOUNDARY_EDGES_ONLY" as const,
      partition_scope_refs: [business_partition],
      period_scope_ref_or_null: period_scope,
      scope_widening_policy: "NO_TENANT_CLIENT_OR_SCOPE_WIDENING" as const,
      tenant_id,
    },
    prior_manifest_id,
  };
}

test("derives stable graph addresses and typed topology for gate support", () => {
  const first = fixture();
  const second = fixture();

  expect(first.graph_id).toBe(second.graph_id);
  expect(first.graph_address).toBe(second.graph_address);
  expect(first.nodes.every((node) => node.graph_address.startsWith("provenance-graph:/"))).toBe(
    true,
  );
  expect(first.nodes.find((node) => node.node_family === "EN_GATE_DECISION")?.node_class).toBe(
    "ENTITY",
  );
  expect(first.nodes.find((node) => node.node_family === "AC_EVALUATE_GATE")?.node_class).toBe(
    "ACTIVITY",
  );
  expect(first.edges.find((edge) => edge.edge_type === "ED_CONTRADICTS")).toMatchObject({
    admissibility_state: "LIMITED",
    limitation_codes: ["EXPLICIT_CONTRADICTION"],
  });
});

test("keeps gate decisions generated by AC_EVALUATE_GATE and explicit lineage boundaries", () => {
  const data = fixture();
  const lineageEdge = data.edges.find((edge) => edge.edge_type === "ED_CONTINUES");

  expect(lineageEdge).toBeTruthy();
  expect(lineageEdge?.from_manifest_id).toBe(data.manifest_id);
  expect(lineageEdge?.to_manifest_id).toBe(data.prior_manifest_id);
  expect(lineageBoundaryIdForEdge(lineageEdge!)).toMatch(/^lineage-boundary\./);

  const integrity = validateGraphIntegrity({
    edges: data.edges,
    nodes: data.nodes,
    paths: [],
  });
  expect(integrity.issues.filter((entry) => entry.code === "GATE_ACTIVITY_MISSING")).toEqual([]);
  expect(integrity.valid).toBe(true);
});
